/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Music_store_Management_Systems;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;
/**
 *
 * @author Bobynero
 */
public class Music_store_Management_System extends javax.swing.JFrame {
double [] articole=new double[5];
double [] instrumente=new double[7];
double [] cost=new double[3];
double [] i=new double[11];
    /**
     * Creates new form Music_store_Management_System
     */
    public Music_store_Management_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        BonFiscal = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ChCorziElectrica = new javax.swing.JCheckBox();
        ChCorziClasica = new javax.swing.JCheckBox();
        ChFastFret = new javax.swing.JCheckBox();
        ChPanaChitara = new javax.swing.JCheckBox();
        ChManualArpegii = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        Corzichitaraelectrica = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Fastfret = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        Corzichitaraclasica = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        Manualarpegii = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        Panachitara = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        Taxa = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        SubTotal = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        LabelTotal = new javax.swing.JTextPane();
        jPanel7 = new javax.swing.JPanel();
        ChChitaraClasica = new javax.swing.JCheckBox();
        ChChitaraElectrica = new javax.swing.JCheckBox();
        ChVioara = new javax.swing.JCheckBox();
        ChClape = new javax.swing.JCheckBox();
        ChTobe = new javax.swing.JCheckBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        Chitaraclasica = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        Tobe = new javax.swing.JTextPane();
        ChMandolina = new javax.swing.JCheckBox();
        jScrollPane19 = new javax.swing.JScrollPane();
        Vioara = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        Clape = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        Mandolina = new javax.swing.JTextPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        Chitaraelectrica = new javax.swing.JTextPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtBonFiscal = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bga = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        CostArticoleInstrumente = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        CostInstrumente = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        Serviciu = new javax.swing.JTextPane();

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jCheckBox11.setText("jCheckBox1");

        jCheckBox12.setText("jCheckBox2");

        jCheckBox13.setText("jCheckBox3");

        jCheckBox14.setText("jCheckBox4");

        jCheckBox15.setText("jCheckBox5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox11))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jCheckBox11)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox12)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox13)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox14)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox15)
                .addGap(40, 40, 40))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jCheckBox21.setText("jCheckBox1");

        jCheckBox22.setText("jCheckBox2");

        jCheckBox23.setText("jCheckBox3");

        jCheckBox24.setText("jCheckBox4");

        jCheckBox25.setText("jCheckBox5");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox25)
                    .addComponent(jCheckBox24)
                    .addComponent(jCheckBox23)
                    .addComponent(jCheckBox22)
                    .addComponent(jCheckBox21))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jCheckBox21)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox22)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox23)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox24)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox25)
                .addGap(40, 40, 40))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        BonFiscal.setText("Bon fiscal");
        BonFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BonFiscalActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Total");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BonFiscal)
                .addGap(10, 10, 10)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BonFiscal)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 360, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Music store Management");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 980, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        ChCorziElectrica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChCorziElectrica.setText("Corzi chitara electrica");
        ChCorziElectrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChCorziElectricaActionPerformed(evt);
            }
        });

        ChCorziClasica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChCorziClasica.setText("Corzi chitara clasica");
        ChCorziClasica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChCorziClasicaMouseClicked(evt);
            }
        });

        ChFastFret.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChFastFret.setText("Fast Fret");
        ChFastFret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChFastFretMouseClicked(evt);
            }
        });

        ChPanaChitara.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChPanaChitara.setText("Pana chitara");
        ChPanaChitara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChPanaChitaraMouseClicked(evt);
            }
        });

        ChManualArpegii.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChManualArpegii.setText("Manual de arpegii");
        ChManualArpegii.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChManualArpegiiMouseClicked(evt);
            }
        });

        Corzichitaraelectrica.setText("0");
        jScrollPane2.setViewportView(Corzichitaraelectrica);

        Fastfret.setText("0");
        jScrollPane3.setViewportView(Fastfret);

        Corzichitaraclasica.setText("0");
        jScrollPane4.setViewportView(Corzichitaraclasica);

        Manualarpegii.setText("0");
        jScrollPane5.setViewportView(Manualarpegii);

        Panachitara.setText("0");
        jScrollPane6.setViewportView(Panachitara);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChCorziClasica)
                            .addComponent(ChFastFret)
                            .addComponent(ChManualArpegii)
                            .addComponent(ChPanaChitara))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ChCorziElectrica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChCorziElectrica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChCorziClasica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChFastFret, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(ChPanaChitara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(ChManualArpegii, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 310, 270));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Taxa");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Subtotal");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total");

        Taxa.setText("0.00");
        jScrollPane15.setViewportView(Taxa);

        SubTotal.setText("0.00");
        jScrollPane16.setViewportView(SubTotal);

        LabelTotal.setText("0.00");
        jScrollPane17.setViewportView(LabelTotal);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(87, 87, 87)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addComponent(jScrollPane15)))
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane15))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane16)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 330, 200));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        ChChitaraClasica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChChitaraClasica.setText("Chitara clasica");
        ChChitaraClasica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChChitaraClasicaMouseClicked(evt);
            }
        });

        ChChitaraElectrica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChChitaraElectrica.setText("Chitara electrica");
        ChChitaraElectrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChChitaraElectricaMouseClicked(evt);
            }
        });

        ChVioara.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChVioara.setText("Vioara");
        ChVioara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChVioaraMouseClicked(evt);
            }
        });

        ChClape.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChClape.setText("Clape");
        ChClape.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChClapeMouseClicked(evt);
            }
        });

        ChTobe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChTobe.setText("Tobe");

        Chitaraclasica.setText("0");
        jScrollPane8.setViewportView(Chitaraclasica);

        Tobe.setText("0");
        jScrollPane11.setViewportView(Tobe);

        ChMandolina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChMandolina.setText("Mandolina");
        ChMandolina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChMandolinaMouseClicked(evt);
            }
        });

        Vioara.setText("0");
        jScrollPane19.setViewportView(Vioara);

        Clape.setText("0");
        jScrollPane20.setViewportView(Clape);

        Mandolina.setText("0");
        jScrollPane9.setViewportView(Mandolina);

        Chitaraelectrica.setText("0");
        jScrollPane21.setViewportView(Chitaraelectrica);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(ChMandolina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(ChChitaraClasica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addComponent(ChChitaraElectrica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(ChVioara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(ChClape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(ChTobe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChMandolina)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChChitaraClasica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChChitaraElectrica, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(ChVioara, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ChClape, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(ChTobe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 290, 270));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtxtBonFiscal.setColumns(20);
        jtxtBonFiscal.setRows(5);
        jScrollPane1.setViewportView(jtxtBonFiscal);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 360, 390));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Cost Articole muzicale");
        jLabel6.setToolTipText("");

        bga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bga.setText("Cost instrumente");
        bga.setName(""); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Taxa de serviciu");

        CostArticoleInstrumente.setBackground(new java.awt.Color(240, 240, 240));
        CostArticoleInstrumente.setText("0");
        jScrollPane12.setViewportView(CostArticoleInstrumente);

        CostInstrumente.setBackground(new java.awt.Color(240, 240, 240));
        CostInstrumente.setText("0");
        CostInstrumente.setName(""); // NOI18N
        jScrollPane13.setViewportView(CostInstrumente);
        CostInstrumente.getAccessibleContext().setAccessibleName("");

        Serviciu.setBackground(new java.awt.Color(240, 240, 240));
        Serviciu.setText("1.5");
        jScrollPane14.setViewportView(Serviciu);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(bga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bga, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        bga.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 270, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CostInstrumente.setText("0");
        CostArticoleInstrumente.setText("0");
        Serviciu.setText("0");
        Taxa.setText("0");
        SubTotal.setText("0");
        LabelTotal.setText("0");
        Corzichitaraelectrica.setText("0");
        Corzichitaraclasica.setText("0");
        Fastfret.setText("0");
        Panachitara.setText("0");
        Manualarpegii.setText("0");
        Mandolina.setText("0");
        Chitaraclasica.setText("0");
        Chitaraelectrica.setText("0");
        Vioara.setText("0");
        Clape.setText("0");
        Tobe.setText("0");
        jtxtBonFiscal.setText(null);
        ChCorziElectrica.setSelected(false);
        ChCorziClasica.setSelected(false);
        ChFastFret.setSelected(false);
        ChPanaChitara.setSelected(false);
        ChManualArpegii.setSelected(false);
        ChMandolina.setSelected(false);
        ChChitaraClasica.setSelected(false);
        ChChitaraElectrica.setSelected(false);
        ChVioara.setSelected(false);
        ChClape.setSelected(false);
        ChTobe.setSelected(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BonFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BonFiscalActionPerformed
        articole[0]=Double.parseDouble(Corzichitaraelectrica.getText());
        articole[1]=Double.parseDouble(Corzichitaraclasica.getText());
        articole[2]=Double.parseDouble(Fastfret.getText());
        articole[3]=Double.parseDouble(Panachitara.getText());
        articole[4]=Double.parseDouble(Manualarpegii.getText());
        instrumente[0]=Double.parseDouble(Mandolina.getText());
        instrumente[2]=Double.parseDouble(Chitaraclasica.getText());
        instrumente[3]=Double.parseDouble(Chitaraelectrica.getText());
        instrumente[4]=Double.parseDouble(Vioara.getText());
        instrumente[5]=Double.parseDouble(Clape.getText());
        instrumente[6]=Double.parseDouble(Tobe.getText());
        cost[0]=Double.parseDouble(Taxa.getText());
        cost[1]=Double.parseDouble(SubTotal.getText());
        cost[2]=Double.parseDouble(LabelTotal.getText());
        //=======================================================
        int refs=1325+(int)(Math.random()*4238);
        //=======================================================
            Calendar timer=Calendar.getInstance();
            timer.getTime();
            SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
            tTime.format(timer.getTime());
            SimpleDateFormat Tdate=new SimpleDateFormat("dd-MMM-yyyy");
            Tdate.format(timer.getTime());
        //=======================================================
        
        jtxtBonFiscal.append(" \t\n Music store Management: \n\n"+
                "Numar bon:\t\t\t"+refs+
                "\nCorzi chitara electrica:\t\t"+articole[0]+
                "\nCorzi chitara clasica:\t\t"+articole[1]+
                "\nFast Fret:\t\t\t"+articole[2]+
                "\nPana chitara:\t\t\t"+articole[3]+
                "\nManual arpegii:\t\t\t"+articole[4]+
                "\n=========================================\t\t"+
                "\nMandolina:\t\t\t"+instrumente[0]+
                "\nChitara clasica:\t\t\t"+instrumente[1]+
                "\nChitara electrica:\t\t"+instrumente[2]+
                "\nVioara:\t\t\t"+instrumente[3]+
                "\nClape:\t\t\t"+instrumente[4]+
                "\nTobe:\t\t\t"+instrumente[5]+
                "\n=========================================\t\t"+
                "\nTaxa:\t\t\t"+cost[0]+  
                "\nSub Total:\t\t\t"+cost[1]+  
                "\nTotal:\t\t\t"+cost[2]+  
                "\n=========================================\t\t"+
                "\nDate: "+Tdate.format(timer.getTime())+
                "\tTime: "+tTime.format(timer.getTime())+
                "\n\nMultumim!");
    }//GEN-LAST:event_BonFiscalActionPerformed

    private void ChCorziElectricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChCorziElectricaActionPerformed
        double ACorziElectrica=Double.parseDouble(CostArticoleInstrumente.getText());
        double CorziElectrica=Double.parseDouble(Corzichitaraelectrica.getText());
        double pretCorziElectrica=70;
        
        if (ChCorziElectrica.isSelected())
        {
            i[0] = (CorziElectrica*pretCorziElectrica)+ACorziElectrica;
            String Articole=String.format("%.2f", i[0]);
            CostArticoleInstrumente.setText(Articole);
            Corzichitaraelectrica.setText(Articole);
            
        }
    }//GEN-LAST:event_ChCorziElectricaActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        articole[0]=Double.parseDouble(CostArticoleInstrumente.getText());
        articole[1]=Double.parseDouble(CostInstrumente.getText());
        articole[2]=Double.parseDouble(Serviciu.getText());
        
        double cTotal=(articole[0]+articole[1]+articole[2]);
        
        String iTaxaTotal=String.format("%.2f", cTotal/100);
        Taxa.setText(iTaxaTotal);
        
        double subTotal=(cTotal);
        String isubTotal=String.format("%.2f", subTotal);
        SubTotal.setText(isubTotal);
        
        double allTotal=(cTotal);
        String iTotal=String.format("%.2f", allTotal + (allTotal/100));
        LabelTotal.setText(iTotal);
        
        String CostA=String.format("%.2f", articole[0]);
        CostArticoleInstrumente.setText(CostA);
        
        String CostI=String.format("%.2f", articole[1]);
        CostInstrumente.setText(CostI);
        
        String Serv=String.format("%.2f", articole[2]);
        Serviciu.setText(Serv);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ChCorziClasicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChCorziClasicaMouseClicked
        double ACorziClasica=Double.parseDouble(CostArticoleInstrumente.getText());
        double CorziClasica=Double.parseDouble(Corzichitaraclasica.getText());
        double pretCorziClasica=33;
        
        if (ChCorziClasica.isSelected())
        {
            i[1] = (CorziClasica*pretCorziClasica)+ACorziClasica;
            String Articole=String.format("%.2f", i[1]);
            CostArticoleInstrumente.setText(Articole);
            Corzichitaraclasica.setText(Articole);
            
        }
    }//GEN-LAST:event_ChCorziClasicaMouseClicked

    private void ChFastFretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChFastFretMouseClicked
        double AFastFret=Double.parseDouble(CostArticoleInstrumente.getText());
        double FastFret=Double.parseDouble(Fastfret.getText());
        double pretFastFret=90;
        
        if (ChFastFret.isSelected())
        {
            i[2] = (FastFret*pretFastFret)+AFastFret;
            String Articole=String.format("%.2f", i[2]);
            CostArticoleInstrumente.setText(Articole);
            Fastfret.setText(Articole);
            
        }
    }//GEN-LAST:event_ChFastFretMouseClicked

    private void ChPanaChitaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChPanaChitaraMouseClicked
        double APanaChitara=Double.parseDouble(CostArticoleInstrumente.getText());
        double PanaChitara=Double.parseDouble(Panachitara.getText());
        double pretPanaChitara=4;
        
        if (ChPanaChitara.isSelected())
        {
            i[3] = (PanaChitara*pretPanaChitara)+APanaChitara;
            String Articole=String.format("%.2f", i[3]);
            CostArticoleInstrumente.setText(Articole);
            Panachitara.setText(Articole);
            
        }
    }//GEN-LAST:event_ChPanaChitaraMouseClicked

    private void ChManualArpegiiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChManualArpegiiMouseClicked
        double AManualArpegii=Double.parseDouble(CostArticoleInstrumente.getText());
        double ManualArpegii=Double.parseDouble(Manualarpegii.getText());
        double pretManualArpegii=100;
        
        if (ChManualArpegii.isSelected())
        {
            i[4] = (ManualArpegii*pretManualArpegii)+AManualArpegii;
            String Articole=String.format("%.2f", i[4]);
            CostArticoleInstrumente.setText(Articole);
            Manualarpegii.setText(Articole);
            
        }
    }//GEN-LAST:event_ChManualArpegiiMouseClicked

    private void ChMandolinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChMandolinaMouseClicked
        double AMandolina=Double.parseDouble(CostInstrumente.getText());
        double Mandolina1=Double.parseDouble(Mandolina.getText());
        double pretMandolina=350;
        
        if (ChMandolina.isSelected())
        {
            i[5] = (Mandolina1*pretMandolina)+AMandolina;
            String Articole=String.format("%.2f", i[5]);
            CostInstrumente.setText(Articole);
            Mandolina.setText(Articole);
            
        }
    }//GEN-LAST:event_ChMandolinaMouseClicked

    private void ChChitaraClasicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChChitaraClasicaMouseClicked
        double AChitaraClasica=Double.parseDouble(CostInstrumente.getText());
        double ChitaraClasica=Double.parseDouble(Chitaraclasica.getText());
        double pretChitaraclasica=750;
        
        if (ChChitaraClasica.isSelected())
        {
            i[6] = (ChitaraClasica*pretChitaraclasica)+AChitaraClasica;
            String Articole=String.format("%.2f", i[6]);
            CostInstrumente.setText(Articole);
            Chitaraclasica.setText(Articole);
            
        }
    }//GEN-LAST:event_ChChitaraClasicaMouseClicked

    private void ChChitaraElectricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChChitaraElectricaMouseClicked
        double AChitaraElectrica=Double.parseDouble(CostInstrumente.getText());
        double ChitaraElectrica=Double.parseDouble(Chitaraelectrica.getText());
        double pretChitaraElectrica=350;
        
        if (ChChitaraElectrica.isSelected())
        {
            i[7] = (ChitaraElectrica*pretChitaraElectrica)+AChitaraElectrica;
            String Articole=String.format("%.2f", i[7]);
            CostInstrumente.setText(Articole);
            Chitaraelectrica.setText(Articole);
            
        }
    }//GEN-LAST:event_ChChitaraElectricaMouseClicked

    private void ChVioaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChVioaraMouseClicked
        double AVioara=Double.parseDouble(CostInstrumente.getText());
        double Vioara1=Double.parseDouble(Vioara.getText());
        double pretVioara=1000;
        
        if (ChVioara.isSelected())
        {
            i[8] = (Vioara1*pretVioara)+AVioara;
            String Articole=String.format("%.2f", i[8]);
            CostInstrumente.setText(Articole);
            Vioara.setText(Articole);
            
        }
    }//GEN-LAST:event_ChVioaraMouseClicked

    private void ChClapeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChClapeMouseClicked
        double AClape=Double.parseDouble(CostInstrumente.getText());
        double Clape1=Double.parseDouble(Clape.getText());
        double pretClape=2000;
        
        if (ChClape.isSelected())
        {
            i[9] = (Clape1*pretClape)+AClape;
            String Articole=String.format("%.2f", i[9]);
            CostInstrumente.setText(Articole);
            Clape.setText(Articole);
            
        }
    }//GEN-LAST:event_ChClapeMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Music_store_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Music_store_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Music_store_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Music_store_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Music_store_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BonFiscal;
    private javax.swing.JCheckBox ChChitaraClasica;
    private javax.swing.JCheckBox ChChitaraElectrica;
    private javax.swing.JCheckBox ChClape;
    private javax.swing.JCheckBox ChCorziClasica;
    private javax.swing.JCheckBox ChCorziElectrica;
    private javax.swing.JCheckBox ChFastFret;
    private javax.swing.JCheckBox ChMandolina;
    private javax.swing.JCheckBox ChManualArpegii;
    private javax.swing.JCheckBox ChPanaChitara;
    private javax.swing.JCheckBox ChTobe;
    private javax.swing.JCheckBox ChVioara;
    private javax.swing.JTextPane Chitaraclasica;
    private javax.swing.JTextPane Chitaraelectrica;
    private javax.swing.JTextPane Clape;
    private javax.swing.JTextPane Corzichitaraclasica;
    private javax.swing.JTextPane Corzichitaraelectrica;
    private javax.swing.JTextPane CostArticoleInstrumente;
    private javax.swing.JTextPane CostInstrumente;
    private javax.swing.JTextPane Fastfret;
    private javax.swing.JTextPane LabelTotal;
    private javax.swing.JTextPane Mandolina;
    private javax.swing.JTextPane Manualarpegii;
    private javax.swing.JTextPane Panachitara;
    private javax.swing.JTextPane Serviciu;
    private javax.swing.JTextPane SubTotal;
    private javax.swing.JTextPane Taxa;
    private javax.swing.JTextPane Tobe;
    private javax.swing.JTextPane Vioara;
    private javax.swing.JLabel bga;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jtxtBonFiscal;
    // End of variables declaration//GEN-END:variables
}
